src/DeliveryBookingProject/Controllers/CustomerController.cs
using DeliveryBookingProject.Models;
using DeliveryBookingProject.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace DeliveryBookingProject.Controllers
{
    [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true,Duration =0)]
    public class CustomerController : Controller
    {
        private IRepo<Customer> _repoCustomer;
        private IRepo<DeliveryExecutive> _repoExecutive;
        private IRepo<DeliveryBooking> _repoBooking;
        private ILogger<CustomerController> _logger;
        public CustomerController(IRepo<Customer> repoCustomer,IRepo<DeliveryExecutive> repoExecutive,IRepo<DeliveryBooking> repoBooking, ILogger<CustomerController> logger)
        {
            _repoCustomer = repoCustomer;
            _repoExecutive = repoExecutive;
            _repoBooking = repoBooking;
            _logger = logger;
        }

        [HttpGet]
        //GET: CustomerController/Register
        public ActionResult Register()
        {
            if (TempData.Count() > 1 && TempData.Count() >= 3)
            {
                return RedirectToAction("Home", "Customer");    //from Customer Controller
            }
            else if (TempData.Count() > 1 && TempData.Count() == 2)
            {
                return RedirectToAction("Home", "Executive");   //from Executive Controller
            }
            else if (TempData.Count() == 1)
            {
                return RedirectToAction("Home", "Admin");        //from Admin Controller
            }
            else
            {
                return View();                         //from User or Home Controller
            }
        }
        [HttpPost]
        public ActionResult Register(Customer customer)
        {
            if (TempData.Count() > 1 && TempData.Count() >= 3)
            {
                return RedirectToAction("Home", "Customer");    //from Customer Controller
            }else if (TempData.Count() > 1 && TempData.Count() == 2)
            {
                return RedirectToAction("Home", "Executive");   //from Executive Controller
            }else if (TempData.Count() == 1)
            {
                return RedirectToAction("Home", "Admin");       //from Admin Controller
            }else
            {
                if (ModelState.IsValid)
                {
                    var record = _repoCustomer.GetByUserName(customer.UserName);
                    if (record == null && customer.UserName != "Apple")
                    {
                        customer.IsVerified = "Requested";
                        customer.City = customer.City.ToLower();
                        bool result=_repoCustomer.AddInfo(customer);
                        if(result == true)
                        {
                            TempData["Success"] = "Registered";
                            TempData["UserName"] = customer.UserName;
                            return View();
                        }
                        else
                        {
                            TempData["Msg"] = "Not Registered";
                            return RedirectToAction("Error");
                        }
                        
                    }else
                    {
                        TempData["Msg"] = "UserName Exists";
                        return RedirectToAction("Error");
                    }
                }else
                {
                    return View(customer);
                }                                                   //from User or Home Controller
            }
        }
        public IActionResult CustomerLogin(User user)
        {
            string UserName = user.UserName;
            Customer Records = _repoCustomer.GetByUserName(UserName);
            if (Records != null && Records.Password == user.Password) 
            {
                if(Records.IsVerified == "Verified")
                {
                    TempData["UserID"] = Records.CustomerId;
                    TempData["City"] = Records.City;
                    //TempData["UserName"] = Records.UserName;
                    TempData["Cust_Name"] = Records.CustomerName;
                    return RedirectToAction("Home");
                }
                else
                {
                    TempData["ErrMsg"] = "Your Account was Not Verified";
                    return RedirectToAction("Error", "User");
                }
            }
            else
            {
                //alert Incorrect UserName Or Password
                TempData["ErrMsg"] = "Incorrect UserName or Password";
                return RedirectToAction("Error", "User");
            }
        }
        public ActionResult Home()
        {
            if (TempData.Count() > 1 && TempData.Count() >= 3)
            {
                int id = Convert.ToInt32(TempData.Peek("UserID"));
                return View();                                   //from Customer Controller
            }
            else if (TempData.Count() > 1 && TempData.Count() == 2)
            {
                return RedirectToAction("Home", "Executive");   //from Executive Controller
            }
            else if (TempData.Count() == 1)
            {
                return RedirectToAction("Home", "Admin");       //from Admin Controller
            }
            else
            {
                return RedirectToAction("Index", "Home");       //from User or Home Controller
            }
        }
        public ActionResult Profile()
        {
            if (TempData.Count() > 1 && TempData.Count() >= 3)
            {
                try
                {
                    int Cust_id = Convert.ToInt32(TempData.Peek("UserId"));
                    Customer customer = _repoCustomer.GetById(Cust_id);
                    if (customer != null)
                    {
                        return View(customer);
                    }
                    else
                    {
                        return View(customer);
                    }
                }
                catch (Exception e)
                {
                    _logger.LogError(e.Message);
                    return View();
                }                                              //from Customer Controller
            }
            else if (TempData.Count() > 1 && TempData.Count() == 2)
            {
                return RedirectToAction("Home", "Executive");   //from Executive Controller
            }
            else if (TempData.Count() == 1)
            {
                return RedirectToAction("Home", "Admin");         //from Admin Controller
            }
            else
            {
                return RedirectToAction("Index", "Home");       //from User or Home Controller
            }
        }
        [HttpGet]
        // GET: CustomerController/Edit/5
        public ActionResult EditCustomerInfo()
        {
            if (TempData.Count() > 1 && TempData.Count() >= 3)
            {
                try
                {
                    int id = Convert.ToInt32(TempData.Peek("UserID"));
                    Customer customer = _repoCustomer.GetById(id);
                    return View(customer);
                }
                catch (Exception e)
                {
                    _logger.LogError(e.Message);
                    return View();
                }                                              //from Customer Controller
            }
            else if (TempData.Count() > 1 && TempData.Count() == 2)
            {
                return RedirectToAction("Home", "Executive");   //from Executive Controller
            }
            else if (TempData.Count() == 1)
            {
                return RedirectToAction("Home", "Admin");        //from Admin Controller
            }
            else
            {
                return RedirectToAction("Index", "Home");       //from User or Home Controller
            }
        }

        // POST: CustomerController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditCustomerInfo(Customer customer)
        {
            if (TempData.Count() > 1 && TempData.Count() >= 3)
            {
                try
                {
                    if (ModelState.IsValid)
                    {
                        _repoCustomer.EditInfo(customer);
                        return RedirectToAction("Profile");
                    }
                    else
                    {
                        return View(customer);
                    }
                }
                catch (Exception e)
                {
                    _logger.LogError(e.Message);
                    return View();
                }                                                //from Customer Controller
            }
            else if (TempData.Count() > 1 && TempData.Count() == 2)
            {
                return RedirectToAction("Home", "Executive");   //from Executive Controller
            }
            else if (TempData.Count() == 1)
            {
                return RedirectToAction("Home", "Admin");        //from Admin Controller
            }
            else
            {
                return RedirectToAction("Index", "Home");       //from User or Home Controller
            }
        }
        [HttpGet]
        public ActionResult BookingExecutive()
        {
            if (TempData.Count() > 1 && TempData.Count() >= 3)
            {
                try
                {
                    int id = Convert.ToInt32(TempData.Peek("UserID"));
                    string city = TempData.Peek("City").ToString();
                    List<DeliveryExecutive> executives = _repoExecutive.GetAllInfo().Where(a => a.City == city && a.IsVerified == "Verified").ToList();

src/DeliveryBookingProject/Controllers/DeliveryBookController.cs
using DeliveryBookingProject.Models;
using DeliveryBookingProject.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DeliveryBookingProject.Controllers
{
    [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
    public class DeliveryBookController : Controller
    {
        private IRepo<DeliveryBooking> _repoBooking;
        private IRepo<Customer> _repoCustomer;
        private IRepo<DeliveryExecutive> _repoExecutive;
        private ILogger<DeliveryBookController> _logger;
        public DeliveryBookController(IRepo<DeliveryBooking> repoBooking,IRepo<Customer> repoCustomer, IRepo<DeliveryExecutive> repoExecutive, ILogger<DeliveryBookController> logger)
        {
            _repoBooking = repoBooking;
            _repoCustomer = repoCustomer;
            _repoExecutive = repoExecutive;
            _logger = logger;
        }
        [HttpGet("{id}")]
        public ActionResult AddBooking(int Id)
        {
            if (TempData.Count() > 1 && TempData.Count() >= 3)
            {
                DeliveryExecutive executive = _repoExecutive.GetById(Id);
                if(executive!= null && executive.City == TempData.Peek("City").ToString())
                {
                    TempData["Exce_Name"] = executive.ExecutiveName;
                    DeliveryBooking delivery = new DeliveryBooking();
                    delivery.ExecutiveId = Id;
                    return View(delivery);
                }else if(executive == null)
                {
                    TempData["Msg"] = "No Executives";
                    return RedirectToAction("Error", "Customer");
                }
                else
                {
                    TempData["Msg"] = "Selecting Invalid Executive";
                    return RedirectToAction("Error", "Customer");
                }                                                //from Customer Controller
            }
            else if (TempData.Count() > 1 && TempData.Count() == 2)
            {
                return RedirectToAction("Home", "Executive");   //from Executive Controller
            }
            else if (TempData.Count() == 1)
            {
                return RedirectToAction("Home", "Admin");       //from Admin Controller
            }
            else
            {
                return RedirectToAction("Index", "Home");       //from User or Home Controller
            }
        }
        public double CalculatePrice(double kg)
        {
            double PricePerKg = kg * 100, petrol = 200.0,gst =  0.02 ;
            double price = PricePerKg + petrol;
            gst = price * gst;
            price = price + gst;
            return price;
        }
        [HttpPost("{id}")]
        public ActionResult AddBooking(DeliveryBooking booking)
        {
            if (TempData.Count() > 1 && TempData.Count() >= 3)
            {
                try
                {
                    int Cust_id = Convert.ToInt32(TempData.Peek("UserID"));
                    booking.CustomerId = Cust_id;
                    booking.OrderDate = DateTime.Today;
                    List<DeliveryBooking> Records = _repoBooking.GetAllInfo().Where(a => a.CustomerId == Cust_id && a.PickUpDateTime.Date == booking.PickUpDateTime.Date).ToList();// checking Whether they Have Same Day on Delivery (in Process-- && a.BookingStatus.Equals(a.BookingStatus == "CustomerRequest" || a.BookingStatus == "ExecutiveAccept")
                    if (ModelState.IsValid)
                    {
                        if (Records.Count == 0)
                        {
                            booking.BookingStatus = "CustomerRequest";
                            booking.Price = CalculatePrice(booking.WeightOfPackage);
                            bool result = _repoBooking.AddInfo(booking);
                            if (result == true)
                            {
                                TempData["BSuccess"] = "BookingAdded";
                                TempData["CustId"] = Cust_id;
                                return View();
                            }
                            else
                            {
                                TempData["Msg"] = "Not BookingAdded";
                                return RedirectToAction("Error", "Customer");
                            }
                        }
                        else
                        {
                            TempData["Msg"] = "Booking Is Exists";
                            return RedirectToAction("Error", "Customer");
                        }
                    }
                    else
                    {
                        return View(Records);//check
                    }
                }
                catch (Exception e)
                {
                    _logger.LogError(e.Message);
                    TempData["Msg"] = "Booking Is IN Error Check Log";
                    return RedirectToAction("Error", "Customer");
                }                                                 //from Customer Controller
            }
            else if (TempData.Count() > 1 && TempData.Count() == 2)
            {
                return RedirectToAction("Home", "Executive");   //from Executive Controller
            }
            else if (TempData.Count() == 1)
            {
                return RedirectToAction("Home", "Admin");       //from Admin Controller
            }
            else
            {
                return RedirectToAction("Index", "Home");       //from User or Home Controller
            }
        }
        
    }
}

src/DeliveryBookingProject/Controllers/HomeController.cs
using DeliveryBookingProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace DeliveryBookingProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            TempData.Clear();
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        public ActionResult ContactUs()
        {
            return View();
        }
    }
}

src/DeliveryBookingProject/Views/Customer/BookingDetailById.cshtml
@model DeliveryBookingProject.Models.DeliveryBooking

@{
    ViewData["Title"] = "BookingDetailById";
}
<link rel="stylesheet" href="~/css/site.css" />
<h1>Booking Details</h1>

<div>
    <hr />
    @if (Model != null)
    {
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.ExecutiveId)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.ExecutiveId)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.OrderDate)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.OrderDate)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.PickUpDateTime)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.PickUpDateTime)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.BookingStatus)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.BookingStatus)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Message)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Message)
            </dd>
            @if (Model.ResMessage != null)
            {
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.ResMessage)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.ResMessage)
                </dd>
            }
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.WeightOfPackage)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.WeightOfPackage)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Price)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Price)
            </dd>
        </dl>
    }
    else
    {
        <h4>No More Details</h4>
    }
</div>

src/DeliveryBookingProject/Views/Customer/BookingDetails.cshtml
@model IEnumerable<DeliveryBookingProject.Models.DeliveryBooking>

@{
    ViewData["Title"] = "BookingDetails";
}
<link rel="stylesheet" href="~/css/site.css" />
<h1> Ordered Details </h1>
@if (Model != null)
{
    double total = 0;
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ExecutiveId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.OrderDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PickUpDateTime)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.BookingStatus)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.WeightOfPackage)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Price)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    @using (Html.BeginForm("BookingDetailById", "Customer", new { Id = item.OrderId }))
                    {
                        <td>
                            @Html.DisplayFor(modelItem => item.ExecutiveId)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.OrderDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PickUpDateTime)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.BookingStatus)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.WeightOfPackage)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Price)
                        </td>
                        <td>
                            <input type="submit" class="btn btn-success" name="Details" value="Details" />
                        </td>
                        @if (item.BookingStatus == "PackagePickUped")
                        {
                            total = total + item.Price;
                        }
                    }
                </tr>
            }
            <tr></tr>
            <tr>
                @if (total != 0)
                {
                    <th>
                        <label>Total Payable Cash:</label>
                    </th>
                    <td>
                        <label>Rs.@total</label>
                    </td>
                }
            </tr>
        </tbody>
    </table>
}
else
{
    <h4>No More Order's From You</h4>
}

src/DeliveryBookingProject/Views/Customer/BookingExecutive.cshtml
@model IEnumerable<DeliveryBookingProject.Models.DeliveryExecutive>

@{
    ViewData["Title"] = "BookingExecutive";
}
<link rel="stylesheet" href="~/css/site.css" />
<h1>Booking Executive</h1>
@if (Model != null)
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ExecutiveName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Phone)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Address)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.City)
                </th>
                <th>
                    @Html.Display("Booking")
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    @using (Html.BeginForm("AddBooking", "DeliveryBook", new { Id = item.ExecutiveId}, FormMethod.Get))
                    {
                        <td>
                            @Html.DisplayFor(modelItem => item.ExecutiveName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Phone)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Address)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.City)
                        </td>
                        <td>
                            <input type="submit" class="btn btn-primary" value="Select" />
                        </td>
                    }
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <h4>Not Available Delivery Executive From Your City</h4>
}

src/DeliveryBookingProject/Views/Customer/BookingStatus.cshtml
@model IEnumerable<DeliveryBookingProject.Models.DeliveryBooking>

@{
    ViewData["Title"] = "BookingStatus";
}
<link rel="stylesheet" href="~/css/site.css" />
<h1>Track Order on Progress</h1>
@if (Model != null)
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ExecutiveId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.OrderDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PickUpDateTime)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.BookingStatus)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.WeightOfPackage)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Price)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    @using (Html.BeginForm("BookingDetailById", "Customer", new { Id = item.OrderId }))
                    {
                        <td>
                            @Html.DisplayFor(modelItem => item.ExecutiveId)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.OrderDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PickUpDateTime)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.BookingStatus)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.WeightOfPackage)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Price)
                        </td>
                        <td>
                            <input type="submit" class="btn btn-success" name="Details" value="Details" />
                        </td>
                    }
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <script>
        alert("No More Booking Pending For You");
    </script>
    <h4>No More Booking Pending For You</h4>
}

src/DeliveryBookingProject/Views/Customer/DeleteCustomerInfo.cshtml
@model DeliveryBookingProject.Models.Customer

@{
    ViewData["Title"] = "DeleteCustomerInfo";
}
<link rel="stylesheet" href="~/css/site.css" />
<h1>DeleteCustomerInfo</h1>

<h3>Are you sure you want to delete this?</h3>
<h3>If Click Delete You Should Navigate to Login Page</h3>
<div>
    <h4>Customer</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CustomerName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CustomerName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
    </dl>
    
    <form asp-action="DeleteCustomerInfo">
        <input type="hidden" asp-for="CustomerId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        @Html.ActionLink("Cancel", "Home") 
    </form>
</div>

src/DeliveryBookingProject/Views/Customer/EditCustomerInfo.cshtml
@model DeliveryBookingProject.Models.Customer

@{
    ViewData["Title"] = "EditInfo";
}
<link rel="stylesheet" href="~/css/site.css" />
<h1>EditCustomerInfo</h1>

<h4>Customer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        @if (Model != null)
        {
            <form asp-action="EditCustomerInfo">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="CustomerId" />
                <input type="hidden" asp-for="IsVerified" />
                <div class="form-group">
                    <label asp-for="CustomerName" class="control-label"></label>
                    <input asp-for="CustomerName" class="form-control" />
                    <span asp-validation-for="CustomerName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="UserName" class="control-label"></label>
                    <input asp-for="UserName" class="form-control" />
                    <span asp-validation-for="UserName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Password" class="control-label"></label>
                    <input type="password" asp-for="Password" class="form-control" />
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Age" class="control-label"></label>
                    <input asp-for="Age" class="form-control" />
                    <span asp-validation-for="Age" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Phone" class="control-label"></label>
                    <input asp-for="Phone" class="form-control" />
                    <span asp-validation-for="Phone" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Address" class="control-label"></label>
                    <input asp-for="Address" class="form-control" />
                    <span asp-validation-for="Address" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="City" class="control-label"></label>
                    <input asp-for="City" class="form-control" />
                    <span asp-validation-for="City" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Update" class="btn btn-info" />
                </div>
            </form>
        }
        else
        {
            <script>
                alert("Your Profile Is Removed")
            </script>
        }
    </div>
</div>



@*@section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }*@